services:
  - type: web
    name: barejahospitals
    runtime: python312
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        scope: run_and_build
        value: ${SECRET_KEY}
      - key: FLASK_DEBUG
        scope: run_and_build
        value: "False"
      - key: FLASK_ENV
        scope: run_and_build
        value: production
